development:
  adapter: postgresql
  encoding: unicode
  database: cliq
  host: localhost
  username: cliq
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: cliq_test
  host: localhost
  pool: 5
  username: cliq
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: cliq_production
  pool: 25
  username: cliq
  password:
