development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: welcome.cliq@gmail.com
  :password: cliqapp2014
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: welcome.cliq@gmail.com
  :password: cliqapp2014
  :enable_starttls_auto: true