source 'https://rubygems.org'


gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'therubyracer'
gem 'bootstrap-sass', '2.1'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'paperclip', '~> 3.0'
gem 'nokogiri'
gem 'protected_attributes'
gem 'turbolinks'
gem 'ancestry'
# install this gem via the command line
gem "thin"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
#gem 'sqlite3'
gem "pg"

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-fileupload-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'omniauth-facebook'
gem 'koala'
gem 'dotenv'
gem "rmagick", :require => 'RMagick'
gem 'will_paginate'

# These gems allow us to apply css to html emails
gem 'premailer-rails'
gem 'delayed_job_active_record'

group :production do

end

group :development, :test do
	gem 'rspec-rails'
	gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'guard-livereload'
end

group :test do 
	gem 'faker'
	gem 'capybara'
	gem 'database_cleaner'
	gem 'selenium-webdriver'
	gem 'shoulda-matchers'
	gem 'mocha'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

ruby "2.0.0"