source 'https://rubygems.org'


gem 'less-rails'
gem 'therubyracer'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'paperclip', '~> 3.0'
gem 'nokogiri'
gem 'protected_attributes'
gem 'turbolinks'
gem 'faye'

gem "thin"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'


gem "pg"


gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

gem 'rmagick'
gem 'carrierwave'

gem 'rails4-autocomplete'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-fileupload-rails'

gem 'delayed_job_active_record'
gem 'omniauth-facebook'
gem 'koala'
gem 'dotenv'

gem 'will_paginate'

# These gems allow us to apply css to html emails
gem 'premailer-rails'
gem 'ancestry'
gem 'geocoder'

group :production do

end

group :development, :test do
	gem 'rspec-rails'
	gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'faker'
end

group :test do 
	gem 'capybara'
	gem 'database_cleaner'
	gem 'selenium-webdriver'
	gem 'shoulda-matchers'
	gem 'mocha'
end

group :doc do
  gem 'sdoc', require: false
end

ruby "2.0.0"